import { CommentParentTypes } from "reducers/uiReducers/commentsReducer";
import { updateAndSaveLayout } from "actions/pageActions";
import { setComments as setCommentsAction } from "actions/commentActions";

const dsl = {
  widgets: {
    "0": {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1224,
      snapColumns: 16,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 1080,
      containerStyle: "none",
      snapRows: 33,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 12,
      minHeight: 1292,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: ["rqdm58s4q6", "ruwu8ukzq2", "cq1ekex75y"],
    },
    mthmyp0vwk: {
      isVisible: true,
      widgetName: "Canvas1",
      version: 1,
      containerStyle: "none",
      canExtend: false,
      detachFromLayout: true,
      children: [],
      minHeight: 400,
      type: "CANVAS_WIDGET",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: 592,
      topRow: 0,
      bottomRow: 400,
      parentId: "rqdm58s4q6",
      widgetId: "mthmyp0vwk",
    },
    rqdm58s4q6: {
      isVisible: true,
      backgroundColor: "#FFFFFF",
      widgetName: "Container1",
      containerStyle: "card",
      children: ["mthmyp0vwk"],
      version: 1,
      type: "CONTAINER_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 1,
      rightColumn: 9,
      topRow: 1,
      bottomRow: 11,
      parentId: "0",
      widgetId: "rqdm58s4q6",
    },
    m38sd0evns: {
      isVisible: true,
      widgetName: "Canvas3",
      version: 1,
      containerStyle: "none",
      canExtend: false,
      detachFromLayout: true,
      children: [],
      minHeight: 400,
      type: "CANVAS_WIDGET",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: 592,
      topRow: 0,
      bottomRow: 400,
      parentId: "ruwu8ukzq2",
      widgetId: "m38sd0evns",
    },
    ruwu8ukzq2: {
      isVisible: true,
      backgroundColor: "#FFFFFF",
      widgetName: "Container2",
      containerStyle: "card",
      children: ["m38sd0evns"],
      version: 1,
      type: "CONTAINER_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 1,
      rightColumn: 9,
      topRow: 15,
      bottomRow: 25,
      parentId: "0",
      widgetId: "ruwu8ukzq2",
    },
    cq1ekex75y: {
      isVisible: true,
      backgroundColor: "#FFFFFF",
      widgetName: "Container3",
      containerStyle: "card",
      children: ["95otxmhx6g"],
      version: 1,
      type: "CONTAINER_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 1,
      rightColumn: 9,
      topRow: 29,
      bottomRow: 39,
      parentId: "0",
      widgetId: "cq1ekex75y",
    },
    "95otxmhx6g": {
      isVisible: true,
      widgetName: "Canvas4",
      version: 1,
      containerStyle: "none",
      canExtend: false,
      detachFromLayout: true,
      children: [],
      minHeight: 400,
      type: "CANVAS_WIDGET",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: 592,
      topRow: 0,
      bottomRow: 400,
      parentId: "cq1ekex75y",
      widgetId: "95otxmhx6g",
    },
  },
};

export const updateLayout = () => updateAndSaveLayout(dsl.widgets as any);

export const setComments = () => {
  const comments = Object.entries(dsl.widgets).map(([widgetId], index) => {
    return {
      parentType: CommentParentTypes.widget,
      refId: widgetId,
      meta: {
        position: { top: 10, left: 15 },
      },
      body: widgetId,
      id: `${index}`,
    };
  });

  return setCommentsAction(comments);
};
